version: '3.8'

services:
  zookeeper1:
    container_name: zookeeper1
    restart: always
    image: zookeeper:3.7.0
    ports: 
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "${ZOO_SERVERS}"
      ZOO_TICK_TIME: "${ZOO_TICK_TIME}"
      ZOO_INIT_LIMIT: "${ZOO_INIT_LIMIT}"
      ZOO_SYNC_LIMIT: "${ZOO_SYNC_LIMIT}"
      ZOO_MAX_CLIENT_CNXNS: "${ZOO_MAX_CLIENT_CNXNS}"
      ZOO_CFG_EXTRA: "${ZOO_CFG_EXTRA}"
      ZOO_LOG4J_PROP: "${ZOO_LOG4J_PROP}"

  zookeeper2:
    container_name: zookeeper2
    restart: always
    image: zookeeper:3.7.0
    ports: 
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "${ZOO_SERVERS}"
      ZOO_TICK_TIME: "${ZOO_TICK_TIME}"
      ZOO_INIT_LIMIT: "${ZOO_INIT_LIMIT}"
      ZOO_SYNC_LIMIT: "${ZOO_SYNC_LIMIT}"
      ZOO_MAX_CLIENT_CNXNS: "${ZOO_MAX_CLIENT_CNXNS}"
      ZOO_CFG_EXTRA: "${ZOO_CFG_EXTRA}"
      ZOO_LOG4J_PROP: "${ZOO_LOG4J_PROP}"

  zookeeper3:
    container_name: zookeeper3
    restart: always
    image: zookeeper:3.7.0
    ports: 
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: "${ZOO_SERVERS}"
      ZOO_TICK_TIME: "${ZOO_TICK_TIME}"
      ZOO_INIT_LIMIT: "${ZOO_INIT_LIMIT}"
      ZOO_SYNC_LIMIT: "${ZOO_SYNC_LIMIT}"
      ZOO_MAX_CLIENT_CNXNS: "${ZOO_MAX_CLIENT_CNXNS}"
      ZOO_CFG_EXTRA: "${ZOO_CFG_EXTRA}"
      ZOO_LOG4J_PROP: "${ZOO_LOG4J_PROP}"

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports: 
      - 9092:9092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      KAFKA_DELETE_TOPIC_ENABLE: "${KAFKA_DELETE_TOPIC_ENABLE}"
      KAFKA_HOME: "${KAFKA_HOME}"
      KAFKA_LOG_DIRS: "${KAFKA_LOG_DIRS}"
      KAFKA_NUM_PARTITIONS: "${KAFKA_NUM_PARTITIONS}"
      KAFKA_MIN_INSYNC_REPLICAS: "${KAFKA_MIN_INSYNC_REPLICAS}"
      KAFKA_LOG_RETENTION_HOURS: "${KAFKA_LOG_RETENTION_HOURS}"
      KAFKA_SEGMENT_BYTES: "${KAFKA_SEGMENT_BYTES}"
      KAFKA_RETENTION_CHECK_INTERVAL_MS: "${KAFKA_RETENTION_CHECK_INTERVAL_MS}"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "${KAFKA_AUTO_CREATE_TOPICS_ENABLE}"
      KAFKA_LOG4J_LOGGERS: "${KAFKA_LOG4J_LOGGERS}"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "${KAFKA_LOG4J_ROOT_LOGLEVEL}"
      KAFKA_TOOLS_LOG4J_LOGLEVEL: "${KAFKA_TOOLS_LOG4J_LOGLEVEL}"
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

<<<<<<< HEAD
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports: 
      - 9093:9092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      KAFKA_DELETE_TOPIC_ENABLE: "${KAFKA_DELETE_TOPIC_ENABLE}"
      KAFKA_HOME: "${KAFKA_HOME}"
      KAFKA_LOG_DIRS: "${KAFKA_LOG_DIRS}"
      KAFKA_NUM_PARTITIONS: "${KAFKA_NUM_PARTITIONS}"
      KAFKA_MIN_INSYNC_REPLICAS: "${KAFKA_MIN_INSYNC_REPLICAS}"
      KAFKA_LOG_RETENTION_HOURS: "${KAFKA_LOG_RETENTION_HOURS}"
      KAFKA_SEGMENT_BYTES: "${KAFKA_SEGMENT_BYTES}"
      KAFKA_RETENTION_CHECK_INTERVAL_MS: "${KAFKA_RETENTION_CHECK_INTERVAL_MS}"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "${KAFKA_AUTO_CREATE_TOPICS_ENABLE}"
      KAFKA_LOG4J_LOGGERS: "${KAFKA_LOG4J_LOGGERS}"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "${KAFKA_LOG4J_ROOT_LOGLEVEL}"
      KAFKA_TOOLS_LOG4J_LOGLEVEL: "${KAFKA_TOOLS_LOG4J_LOGLEVEL}"
    depends_on:
      - zookeeper3
      - zookeeper1
      - zookeeper2

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports: 
      - 9094:9092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: "${KAFKA_ZOOKEEPER_CONNECT}"
      KAFKA_DELETE_TOPIC_ENABLE: "${KAFKA_DELETE_TOPIC_ENABLE}"
      KAFKA_HOME: "${KAFKA_HOME}"
      KAFKA_LOG_DIRS: "${KAFKA_LOG_DIRS}"
      KAFKA_NUM_PARTITIONS: "${KAFKA_NUM_PARTITIONS}"
      KAFKA_MIN_INSYNC_REPLICAS: "${KAFKA_MIN_INSYNC_REPLICAS}"
      KAFKA_LOG_RETENTION_HOURS: "${KAFKA_LOG_RETENTION_HOURS}"
      KAFKA_SEGMENT_BYTES: "${KAFKA_SEGMENT_BYTES}"
      KAFKA_RETENTION_CHECK_INTERVAL_MS: "${KAFKA_RETENTION_CHECK_INTERVAL_MS}"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "${KAFKA_AUTO_CREATE_TOPICS_ENABLE}"
      KAFKA_LOG4J_LOGGERS: "${KAFKA_LOG4J_LOGGERS}"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "${KAFKA_LOG4J_ROOT_LOGLEVEL}"
      KAFKA_TOOLS_LOG4J_LOGLEVEL: "${KAFKA_TOOLS_LOG4J_LOGLEVEL}"
    depends_on:
      - zookeeper3
      - zookeeper1
      - zookeeper2

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: localhost:9092,localhost:9093,localhost:9094
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

networks:
  default:
      name: my-network